import Head from 'next/head';
import EventList from '@/components/events/EventList';
import {GetStaticPropsResult, InferGetStaticPropsType} from 'next';
import {EventType} from '@/types/events/EventTypes';
import {getFeaturedEvents} from '@/utils/apiUtil';

function HomePage(props: InferGetStaticPropsType<typeof getStaticProps>) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div>
        <EventList items={props.events}/>
        {/*<li><Link href="/user">유저 리스트</Link></li>*/}
        {/*<li><Link href="/blog">블로그</Link></li>*/}
      </div>
    </>
  );
}

export const getStaticProps = async (): Promise<GetStaticPropsResult<{ events: EventType[] }>> => {
  const featuredEvents = await getFeaturedEvents();

  return {
    props: {
      events: featuredEvents
    },
    revalidate: 1800
  };
};
export default HomePage;